name: inbreif
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.0.0
  http: ^0.12.0+4
  url_launcher: ^5.4.5
  animated_text_kit: ^2.0.0
  animate_do: ^1.7.2
  cached_network_image: ^2.1.0+1
  share: ^0.6.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
     - images/business.jpg
     - images/enter.jpg
     - images/general.jpg
     - images/health.jpg
     - images/technology.jpg
     - images/science.jpg
     - images/sports.jpg
     - images/ic_launcher.png
